name: Build Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: What version you want?
        options:
          - alpha
          - patch
          - minor
          - major

env:
  NODE_ENV: "production"
  NEXT_PUBLIC_ENV: ${{ vars.NEXT_PUBLIC_ENV }}
  NEXT_PUBLIC_GRAPHQL_URI: ${{ vars.NEXT_PUBLIC_GRAPHQL_URI }}
  NEXT_PUBLIC_REST_API_URI: ${{ vars.NEXT_PUBLIC_REST_API_URI }}

permissions:
  contents: write
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  build-test-and-release:
    runs-on: ubuntu-latest

    environment:
      name: "test"

    steps:
      - name: Run Version
        run: echo "Run ${{ github.event.inputs.version }} Version."

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "12.13.0"

      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci

      - name: Start Bump Version
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "${{ vars.ACTIONS_BOT_EMAIL }}"
          git config --global user.name "${{ vars.ACTIONS_BOT_NAME }}"
          npm run release:${{ github.event.inputs.version }}
          git push --follow-tags origin master